# Generated by Django 5.0 on 2024-01-31 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingstations', '0007_add_charg_rate'),
        ('userapp', '0002_user_db_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='chargingslotbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csLocation', models.CharField(max_length=50)),
                ('csAddress', models.CharField(max_length=50)),
                ('Totalconnectors', models.CharField(max_length=50)),
                ('avconnectors', models.CharField(max_length=50)),
                ('powercapacity', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=50)),
                ('timeSlot', models.CharField(max_length=50)),
                ('Rate', models.CharField(max_length=50)),
                ('Image', models.ImageField(default=True, upload_to='image')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargingstations.charging_reg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user_db')),
            ],
        ),
    ]
