# Generated by Django 5.0 on 2024-02-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_chargingslotbooking_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingslotbooking',
            name='vid',
        ),
    ]
