# Generated by Django 5.0 on 2024-01-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp_db',
            name='Image',
            field=models.ImageField(default=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='comp_db',
            name='PhNumber',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
