# Generated by Django 5.0 on 2024-01-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlaces', '0002_comp_db_image_comp_db_phnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c_category',
            old_name='CID',
            new_name='vid',
        ),
    ]
