# Generated by Django 5.0 on 2023-12-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charging_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YourName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('CompanyName', models.CharField(max_length=30)),
                ('CompanyID', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=70)),
                ('State', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
