# Generated by Django 5.0 on 2023-12-06 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingstations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_charg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Location', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=30)),
                ('Totalconnectors', models.CharField(max_length=30)),
                ('avconnectors', models.CharField(max_length=70)),
                ('powercapacity', models.CharField(max_length=30)),
                ('operator', models.CharField(max_length=10)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargingstations.charging_reg')),
            ],
        ),
    ]
