# Generated by Django 5.0 on 2023-12-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingstations', '0002_add_charg'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_charg',
            name='image',
            field=models.ImageField(default=True, upload_to='profile'),
        ),
    ]
