# Generated by Django 5.0 on 2023-12-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingstations', '0003_add_charg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_charg',
            name='Location',
            field=models.CharField(max_length=50),
        ),
    ]
