# Generated by Django 5.0 on 2023-12-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingstations', '0005_alter_add_charg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='charging_reg',
            name='Image',
            field=models.ImageField(default=1, upload_to='profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charging_reg',
            name='PhNumber',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
