# Generated by Django 5.0 on 2024-02-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargingstations', '0007_add_charg_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_charg',
            name='Name',
        ),
    ]
